### ISSUE TITLE
using Canvas painting

### ISSUE THREAD

**Issue by Alexey-T** [Seenkao/New-ZenGL#4]
Hi.
I don't know is it possible to 'move' my current ATSynEdit component painting to OpenGL, via ZenGL? for that I would need some TCanvas-like object, which supports some or all of TCanvas methods: C.TextOut(x, y, text), C.Line, C.Rectangle, C.FillRect, C.Brush.Color, C.Pen.Color, C.Pixels[x,y].
is it possible to write Canvas-like wrapper which is run over ZenGL?
the GTK2/QT5 text renreding is slow, so I want the option in CudaText to use OpenGL.

**Comment by Seenkao** [comment]
Привет!
Для того чтоб было понятно. Если будешь использовать __LCL__ то __ZenGL__ предоставляет только один контекст окна. Будет это панель управления, форма или ещё что-то. Это должен быть только один компонент (TCanvas), который работает с контекстом __OpenGL__.
Для разработки без __LCL__ подобного, надо будет переделывать очень много. Практически все компоненты, которые будут использоваться в __ATSynEdit__. А значит и методы __TCanvas__: C.TextOut(x, y, text), C.Line, C.Rectangle, C.fillRect, C.Brush.Color, C.Pen.Color, C.Pixels[x,y] надо будет переделывать вручную.
Да, в ZenGL есть уже методы для прорисовки примитивов и текста. Но они работают не так же как методы __TCanvas__. Это  означает, что при вызове методов __TCanvas__ надо либо подгонять под процедуры уже созданные в __ZenGL__. Либо писать на чистом __OpenGL__ данные методы.

Если ты подготовлен к работе с __OpenGL__, то думаю тебе лучше будет это делать вручную. Если ты будешь использовать __OpenGL 3.2__ и выше, то ты не сможешь воспользоваться функциями вывода текста __ZenGL__ в __Linux__. В __Linux__ автоматически отключается устаревший __OpenGL__ если используется версия 3.2 и выше. А все примитивы и текст в ZenGL выводятся с помощью устаревшего __OpenGL__. У меня времени не хватает на всё, чтоб этим заняться.

Потому, могут ответить да, можно, но нужно терпение. И как я писал выше, только для одного контекста. Так как я ввёл возможность использования полного __OpenGL__, то при необходимости могу вернуть возможность работы с несколькими контекстами. Но это скажется на работоспособности приложения. Лучше всего использовать один контекст.
Если будете заниматься, то на моём ютуб-канале я выложил несколько видео, по тому как работать с __OpenGL 3+__ в __ZenGL__. Но только на русском. Но код можно посмотреть. Я его прокручивал, чтоб было видно.
[youtube-video](https://youtu.be/wXd77SR_Xsg)

----
__Google translate:__
Hey!
In order to be clear. If you use __LCL__ then __ZenGL__ provides only one window context. Will it be a control panel, a form or something else. It should only be one component (TCanvas) that works with the __OpenGL__ context.
To develop without __LCL__ like this, it will be necessary to redo a lot. Almost all components that will be used in __ATSynEdit__. This means that the __TCanvas__ methods: C.TextOut(x, y, text), C.Line, C.Rectangle, C.fillRect, C.Brush.Color, C.Pen.Color, C.Pixels[x,y] are will have to be redone manually.
Yes, ZenGL already has methods for drawing primitives and text. But they don't work the same way as __TCanvas__ methods. This means that when calling __TCanvas__ methods, you must either customize the procedures already created in __ZenGL__. Or write these methods in pure __OpenGL__.

If you are prepared to work with __OpenGL__, then I think it would be better for you to do it manually. If you use __OpenGL 3.2__ or later, you will not be able to use ZenGL's text output features on __Linux__. On __Linux__, deprecated __OpenGL__ is automatically disabled if version 3.2 or higher is used. And all primitives and text in __ZenGL__ are rendered using legacy __OpenGL__. I don't have enough time to do everything.

Therefore, they can answer yes, it is possible, but patience is needed. And as I wrote above, only for one context. Since I introduced the ability to use full __OpenGL__, I can return the ability to work with multiple contexts if necessary. But this will affect the performance of the application. It is best to use one context.
If you do, then on my YouTube channel I posted several videos on how to work with __OpenGL 3+__ in __ZenGL__. But only in Russian. But you can see the code. I scrolled it so you can see it.
[youtube-video](https://youtu.be/wXd77SR_Xsg)

**Comment by Alexey-T** [comment]
Понятно, спасибо!

**Comment by Alexey-T** [comment]
Ето для редактора. а он многодокументный. 2-3-4-5-6 табов могут быть видны СРАЗУ рядом. и один контекст - ето могила.
